name: dev
variables:
  - name: baseUrl
    value: https://users.dev.practic.ordocrm.online
    description: ""
  - name: regexLogin
    value: ^[a-z0-9]{3,30}$
    description: Регулярка для login
  - name: regexEmail
    value: ^[^\s@]+@[^\s@]+\.[^\s@]+$
    description: Регулярка для email
