name: local
variables:
  - name: baseUrl
    value: http://127.0.0.1:8081/
    description: ""
  - name: regexLogin
    value: ^[a-z0-9]{3,30}$
    description: Регулярка для login
  - name: regexEmail
    value: ^[^\s@]+@[^\s@]+\.[^\s@]+$
    description: Регулярка для email
